/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace BlueReefRegistry {
  export type ApplicationStruct = {
    id: BigNumberish;
    applicant: AddressLike;
    userType: BigNumberish;
    organizationName: string;
    documentHash: string;
    landCoordinates: string;
    areaHectares: BigNumberish;
    plantSpecies: string;
    status: BigNumberish;
    submissionTimestamp: BigNumberish;
    reviewTimestamp: BigNumberish;
    reviewer: AddressLike;
    reviewComments: string;
    projectContractAddress: AddressLike;
  };

  export type ApplicationStructOutput = [
    id: bigint,
    applicant: string,
    userType: bigint,
    organizationName: string,
    documentHash: string,
    landCoordinates: string,
    areaHectares: bigint,
    plantSpecies: string,
    status: bigint,
    submissionTimestamp: bigint,
    reviewTimestamp: bigint,
    reviewer: string,
    reviewComments: string,
    projectContractAddress: string
  ] & {
    id: bigint;
    applicant: string;
    userType: bigint;
    organizationName: string;
    documentHash: string;
    landCoordinates: string;
    areaHectares: bigint;
    plantSpecies: string;
    status: bigint;
    submissionTimestamp: bigint;
    reviewTimestamp: bigint;
    reviewer: string;
    reviewComments: string;
    projectContractAddress: string;
  };
}

export interface BlueReefRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "DEFAULT_ADMIN_ROLE"
      | "GOVERNMENT_ROLE"
      | "VERIFIER_ROLE"
      | "applications"
      | "getApplication"
      | "getApplicationsByStatus"
      | "getRoleAdmin"
      | "getTotalApplications"
      | "getUserApplications"
      | "getUserType"
      | "grantGovernmentRole"
      | "grantRole"
      | "grantVerifierRole"
      | "hasRole"
      | "isUserRegistered"
      | "registerUser"
      | "registeredUsers"
      | "renounceRole"
      | "revokeRole"
      | "setProjectContract"
      | "submitApplication"
      | "supportsInterface"
      | "updateApplicationStatus"
      | "userApplications"
      | "userTypes"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ApplicationStatusUpdated"
      | "ApplicationSubmitted"
      | "ProjectContractDeployed"
      | "RoleAdminChanged"
      | "RoleGranted"
      | "RoleRevoked"
      | "UserRegistered"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "GOVERNMENT_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "VERIFIER_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "applications",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getApplication",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getApplicationsByStatus",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleAdmin",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalApplications",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getUserApplications",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserType",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "grantGovernmentRole",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "grantRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "grantVerifierRole",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isUserRegistered",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "registerUser",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "registeredUsers",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setProjectContract",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "submitApplication",
    values: [string, string, string, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateApplicationStatus",
    values: [BigNumberish, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "userApplications",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "userTypes",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "GOVERNMENT_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "VERIFIER_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "applications",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getApplication",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getApplicationsByStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRoleAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTotalApplications",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserApplications",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserType",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "grantGovernmentRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "grantVerifierRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isUserRegistered",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerUser",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registeredUsers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setProjectContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitApplication",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateApplicationStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "userApplications",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "userTypes", data: BytesLike): Result;
}

export namespace ApplicationStatusUpdatedEvent {
  export type InputTuple = [
    applicationId: BigNumberish,
    oldStatus: BigNumberish,
    newStatus: BigNumberish,
    reviewer: AddressLike
  ];
  export type OutputTuple = [
    applicationId: bigint,
    oldStatus: bigint,
    newStatus: bigint,
    reviewer: string
  ];
  export interface OutputObject {
    applicationId: bigint;
    oldStatus: bigint;
    newStatus: bigint;
    reviewer: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ApplicationSubmittedEvent {
  export type InputTuple = [
    applicationId: BigNumberish,
    applicant: AddressLike,
    userType: BigNumberish,
    organizationName: string
  ];
  export type OutputTuple = [
    applicationId: bigint,
    applicant: string,
    userType: bigint,
    organizationName: string
  ];
  export interface OutputObject {
    applicationId: bigint;
    applicant: string;
    userType: bigint;
    organizationName: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProjectContractDeployedEvent {
  export type InputTuple = [
    applicationId: BigNumberish,
    projectContract: AddressLike
  ];
  export type OutputTuple = [applicationId: bigint, projectContract: string];
  export interface OutputObject {
    applicationId: bigint;
    projectContract: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleAdminChangedEvent {
  export type InputTuple = [
    role: BytesLike,
    previousAdminRole: BytesLike,
    newAdminRole: BytesLike
  ];
  export type OutputTuple = [
    role: string,
    previousAdminRole: string,
    newAdminRole: string
  ];
  export interface OutputObject {
    role: string;
    previousAdminRole: string;
    newAdminRole: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleGrantedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleRevokedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UserRegisteredEvent {
  export type InputTuple = [
    user: AddressLike,
    userType: BigNumberish,
    organizationName: string
  ];
  export type OutputTuple = [
    user: string,
    userType: bigint,
    organizationName: string
  ];
  export interface OutputObject {
    user: string;
    userType: bigint;
    organizationName: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface BlueReefRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): BlueReefRegistry;
  waitForDeployment(): Promise<this>;

  interface: BlueReefRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  DEFAULT_ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  GOVERNMENT_ROLE: TypedContractMethod<[], [string], "view">;

  VERIFIER_ROLE: TypedContractMethod<[], [string], "view">;

  applications: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        bigint,
        string,
        string,
        string,
        bigint,
        string,
        bigint,
        bigint,
        bigint,
        string,
        string,
        string
      ] & {
        id: bigint;
        applicant: string;
        userType: bigint;
        organizationName: string;
        documentHash: string;
        landCoordinates: string;
        areaHectares: bigint;
        plantSpecies: string;
        status: bigint;
        submissionTimestamp: bigint;
        reviewTimestamp: bigint;
        reviewer: string;
        reviewComments: string;
        projectContractAddress: string;
      }
    ],
    "view"
  >;

  getApplication: TypedContractMethod<
    [_applicationId: BigNumberish],
    [BlueReefRegistry.ApplicationStructOutput],
    "view"
  >;

  getApplicationsByStatus: TypedContractMethod<
    [_status: BigNumberish],
    [bigint[]],
    "view"
  >;

  getRoleAdmin: TypedContractMethod<[role: BytesLike], [string], "view">;

  getTotalApplications: TypedContractMethod<[], [bigint], "view">;

  getUserApplications: TypedContractMethod<
    [_user: AddressLike],
    [bigint[]],
    "view"
  >;

  getUserType: TypedContractMethod<[_user: AddressLike], [bigint], "view">;

  grantGovernmentRole: TypedContractMethod<
    [_account: AddressLike],
    [void],
    "nonpayable"
  >;

  grantRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  grantVerifierRole: TypedContractMethod<
    [_account: AddressLike],
    [void],
    "nonpayable"
  >;

  hasRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;

  isUserRegistered: TypedContractMethod<
    [_user: AddressLike],
    [boolean],
    "view"
  >;

  registerUser: TypedContractMethod<
    [_userType: BigNumberish, _organizationName: string],
    [void],
    "nonpayable"
  >;

  registeredUsers: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  renounceRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  revokeRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  setProjectContract: TypedContractMethod<
    [_applicationId: BigNumberish, _projectContract: AddressLike],
    [void],
    "nonpayable"
  >;

  submitApplication: TypedContractMethod<
    [
      _organizationName: string,
      _documentHash: string,
      _landCoordinates: string,
      _areaHectares: BigNumberish,
      _plantSpecies: string
    ],
    [void],
    "nonpayable"
  >;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  updateApplicationStatus: TypedContractMethod<
    [_applicationId: BigNumberish, _newStatus: BigNumberish, _comments: string],
    [void],
    "nonpayable"
  >;

  userApplications: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  userTypes: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "DEFAULT_ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "GOVERNMENT_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "VERIFIER_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "applications"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        bigint,
        string,
        string,
        string,
        bigint,
        string,
        bigint,
        bigint,
        bigint,
        string,
        string,
        string
      ] & {
        id: bigint;
        applicant: string;
        userType: bigint;
        organizationName: string;
        documentHash: string;
        landCoordinates: string;
        areaHectares: bigint;
        plantSpecies: string;
        status: bigint;
        submissionTimestamp: bigint;
        reviewTimestamp: bigint;
        reviewer: string;
        reviewComments: string;
        projectContractAddress: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getApplication"
  ): TypedContractMethod<
    [_applicationId: BigNumberish],
    [BlueReefRegistry.ApplicationStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getApplicationsByStatus"
  ): TypedContractMethod<[_status: BigNumberish], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getRoleAdmin"
  ): TypedContractMethod<[role: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "getTotalApplications"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getUserApplications"
  ): TypedContractMethod<[_user: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getUserType"
  ): TypedContractMethod<[_user: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "grantGovernmentRole"
  ): TypedContractMethod<[_account: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "grantRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "grantVerifierRole"
  ): TypedContractMethod<[_account: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "hasRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "isUserRegistered"
  ): TypedContractMethod<[_user: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "registerUser"
  ): TypedContractMethod<
    [_userType: BigNumberish, _organizationName: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "registeredUsers"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "renounceRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setProjectContract"
  ): TypedContractMethod<
    [_applicationId: BigNumberish, _projectContract: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "submitApplication"
  ): TypedContractMethod<
    [
      _organizationName: string,
      _documentHash: string,
      _landCoordinates: string,
      _areaHectares: BigNumberish,
      _plantSpecies: string
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "updateApplicationStatus"
  ): TypedContractMethod<
    [_applicationId: BigNumberish, _newStatus: BigNumberish, _comments: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "userApplications"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "userTypes"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  getEvent(
    key: "ApplicationStatusUpdated"
  ): TypedContractEvent<
    ApplicationStatusUpdatedEvent.InputTuple,
    ApplicationStatusUpdatedEvent.OutputTuple,
    ApplicationStatusUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "ApplicationSubmitted"
  ): TypedContractEvent<
    ApplicationSubmittedEvent.InputTuple,
    ApplicationSubmittedEvent.OutputTuple,
    ApplicationSubmittedEvent.OutputObject
  >;
  getEvent(
    key: "ProjectContractDeployed"
  ): TypedContractEvent<
    ProjectContractDeployedEvent.InputTuple,
    ProjectContractDeployedEvent.OutputTuple,
    ProjectContractDeployedEvent.OutputObject
  >;
  getEvent(
    key: "RoleAdminChanged"
  ): TypedContractEvent<
    RoleAdminChangedEvent.InputTuple,
    RoleAdminChangedEvent.OutputTuple,
    RoleAdminChangedEvent.OutputObject
  >;
  getEvent(
    key: "RoleGranted"
  ): TypedContractEvent<
    RoleGrantedEvent.InputTuple,
    RoleGrantedEvent.OutputTuple,
    RoleGrantedEvent.OutputObject
  >;
  getEvent(
    key: "RoleRevoked"
  ): TypedContractEvent<
    RoleRevokedEvent.InputTuple,
    RoleRevokedEvent.OutputTuple,
    RoleRevokedEvent.OutputObject
  >;
  getEvent(
    key: "UserRegistered"
  ): TypedContractEvent<
    UserRegisteredEvent.InputTuple,
    UserRegisteredEvent.OutputTuple,
    UserRegisteredEvent.OutputObject
  >;

  filters: {
    "ApplicationStatusUpdated(uint256,uint8,uint8,address)": TypedContractEvent<
      ApplicationStatusUpdatedEvent.InputTuple,
      ApplicationStatusUpdatedEvent.OutputTuple,
      ApplicationStatusUpdatedEvent.OutputObject
    >;
    ApplicationStatusUpdated: TypedContractEvent<
      ApplicationStatusUpdatedEvent.InputTuple,
      ApplicationStatusUpdatedEvent.OutputTuple,
      ApplicationStatusUpdatedEvent.OutputObject
    >;

    "ApplicationSubmitted(uint256,address,uint8,string)": TypedContractEvent<
      ApplicationSubmittedEvent.InputTuple,
      ApplicationSubmittedEvent.OutputTuple,
      ApplicationSubmittedEvent.OutputObject
    >;
    ApplicationSubmitted: TypedContractEvent<
      ApplicationSubmittedEvent.InputTuple,
      ApplicationSubmittedEvent.OutputTuple,
      ApplicationSubmittedEvent.OutputObject
    >;

    "ProjectContractDeployed(uint256,address)": TypedContractEvent<
      ProjectContractDeployedEvent.InputTuple,
      ProjectContractDeployedEvent.OutputTuple,
      ProjectContractDeployedEvent.OutputObject
    >;
    ProjectContractDeployed: TypedContractEvent<
      ProjectContractDeployedEvent.InputTuple,
      ProjectContractDeployedEvent.OutputTuple,
      ProjectContractDeployedEvent.OutputObject
    >;

    "RoleAdminChanged(bytes32,bytes32,bytes32)": TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;
    RoleAdminChanged: TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;

    "RoleGranted(bytes32,address,address)": TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;
    RoleGranted: TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;

    "RoleRevoked(bytes32,address,address)": TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
    RoleRevoked: TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;

    "UserRegistered(address,uint8,string)": TypedContractEvent<
      UserRegisteredEvent.InputTuple,
      UserRegisteredEvent.OutputTuple,
      UserRegisteredEvent.OutputObject
    >;
    UserRegistered: TypedContractEvent<
      UserRegisteredEvent.InputTuple,
      UserRegisteredEvent.OutputTuple,
      UserRegisteredEvent.OutputObject
    >;
  };
}
