/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace CarbonCreditToken {
  export type CreditBatchStruct = {
    batchId: BigNumberish;
    projectContract: AddressLike;
    amount: BigNumberish;
    mintTimestamp: BigNumberish;
    projectName: string;
    landCoordinates: string;
    ndviReadingId: BigNumberish;
    retired: boolean;
  };

  export type CreditBatchStructOutput = [
    batchId: bigint,
    projectContract: string,
    amount: bigint,
    mintTimestamp: bigint,
    projectName: string,
    landCoordinates: string,
    ndviReadingId: bigint,
    retired: boolean
  ] & {
    batchId: bigint;
    projectContract: string;
    amount: bigint;
    mintTimestamp: bigint;
    projectName: string;
    landCoordinates: string;
    ndviReadingId: bigint;
    retired: boolean;
  };

  export type RetirementRecordStruct = {
    batchId: BigNumberish;
    retiredBy: AddressLike;
    amount: BigNumberish;
    retirementTimestamp: BigNumberish;
    retirementReason: string;
  };

  export type RetirementRecordStructOutput = [
    batchId: bigint,
    retiredBy: string,
    amount: bigint,
    retirementTimestamp: bigint,
    retirementReason: string
  ] & {
    batchId: bigint;
    retiredBy: string;
    amount: bigint;
    retirementTimestamp: bigint;
    retirementReason: string;
  };
}

export interface CarbonCreditTokenInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "DEFAULT_ADMIN_ROLE"
      | "GOVERNMENT_ROLE"
      | "MINTER_ROLE"
      | "PROJECT_ROLE"
      | "allowance"
      | "approve"
      | "authorizeProject"
      | "balanceOf"
      | "burn"
      | "burnFrom"
      | "creditBatches"
      | "deauthorizeProject"
      | "decimals"
      | "decreaseAllowance"
      | "emergencyMint"
      | "getCreditBatch"
      | "getGlobalStats"
      | "getProjectStats"
      | "getRetirementRecord"
      | "getRoleAdmin"
      | "getTotalBatches"
      | "getTotalRetirements"
      | "getUserBatches"
      | "getUserStats"
      | "grantMinterRole"
      | "grantRole"
      | "hasRole"
      | "increaseAllowance"
      | "isAuthorizedProject"
      | "mintCredits"
      | "name"
      | "renounceRole"
      | "retireCredits"
      | "retirements"
      | "revokeRole"
      | "supportsInterface"
      | "symbol"
      | "totalMintedByProject"
      | "totalRetiredByUser"
      | "totalSupply"
      | "totalSupplyMinted"
      | "totalSupplyRetired"
      | "transfer"
      | "transferFrom"
      | "userBatches"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "Approval"
      | "CreditsMinted"
      | "CreditsRetired"
      | "ProjectAuthorized"
      | "ProjectDeauthorized"
      | "RoleAdminChanged"
      | "RoleGranted"
      | "RoleRevoked"
      | "Transfer"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "GOVERNMENT_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MINTER_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PROJECT_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "allowance",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "approve",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "authorizeProject",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "balanceOf",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "burn", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "burnFrom",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "creditBatches",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "deauthorizeProject",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "decimals", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "decreaseAllowance",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "emergencyMint",
    values: [AddressLike, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "getCreditBatch",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getGlobalStats",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getProjectStats",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getRetirementRecord",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleAdmin",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalBatches",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalRetirements",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getUserBatches",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserStats",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "grantMinterRole",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "grantRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "increaseAllowance",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isAuthorizedProject",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "mintCredits",
    values: [
      AddressLike,
      AddressLike,
      BigNumberish,
      string,
      string,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(functionFragment: "name", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "retireCredits",
    values: [BigNumberish, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "retirements",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "symbol", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "totalMintedByProject",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "totalRetiredByUser",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "totalSupply",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalSupplyMinted",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalSupplyRetired",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transfer",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferFrom",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "userBatches",
    values: [AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "GOVERNMENT_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MINTER_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "PROJECT_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "allowance", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "approve", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "authorizeProject",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "balanceOf", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "burn", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "burnFrom", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "creditBatches",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deauthorizeProject",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "decimals", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "decreaseAllowance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "emergencyMint",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCreditBatch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getGlobalStats",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getProjectStats",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRetirementRecord",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRoleAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTotalBatches",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTotalRetirements",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserBatches",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserStats",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "grantMinterRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "increaseAllowance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isAuthorizedProject",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "mintCredits",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "name", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "retireCredits",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "retirements",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "symbol", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "totalMintedByProject",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalRetiredByUser",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalSupply",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalSupplyMinted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalSupplyRetired",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "transfer", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferFrom",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "userBatches",
    data: BytesLike
  ): Result;
}

export namespace ApprovalEvent {
  export type InputTuple = [
    owner: AddressLike,
    spender: AddressLike,
    value: BigNumberish
  ];
  export type OutputTuple = [owner: string, spender: string, value: bigint];
  export interface OutputObject {
    owner: string;
    spender: string;
    value: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CreditsMintedEvent {
  export type InputTuple = [
    batchId: BigNumberish,
    projectContract: AddressLike,
    recipient: AddressLike,
    amount: BigNumberish,
    projectName: string
  ];
  export type OutputTuple = [
    batchId: bigint,
    projectContract: string,
    recipient: string,
    amount: bigint,
    projectName: string
  ];
  export interface OutputObject {
    batchId: bigint;
    projectContract: string;
    recipient: string;
    amount: bigint;
    projectName: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CreditsRetiredEvent {
  export type InputTuple = [
    retirementId: BigNumberish,
    batchId: BigNumberish,
    retiredBy: AddressLike,
    amount: BigNumberish,
    reason: string
  ];
  export type OutputTuple = [
    retirementId: bigint,
    batchId: bigint,
    retiredBy: string,
    amount: bigint,
    reason: string
  ];
  export interface OutputObject {
    retirementId: bigint;
    batchId: bigint;
    retiredBy: string;
    amount: bigint;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProjectAuthorizedEvent {
  export type InputTuple = [
    projectContract: AddressLike,
    authorizer: AddressLike
  ];
  export type OutputTuple = [projectContract: string, authorizer: string];
  export interface OutputObject {
    projectContract: string;
    authorizer: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProjectDeauthorizedEvent {
  export type InputTuple = [
    projectContract: AddressLike,
    deauthorizer: AddressLike
  ];
  export type OutputTuple = [projectContract: string, deauthorizer: string];
  export interface OutputObject {
    projectContract: string;
    deauthorizer: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleAdminChangedEvent {
  export type InputTuple = [
    role: BytesLike,
    previousAdminRole: BytesLike,
    newAdminRole: BytesLike
  ];
  export type OutputTuple = [
    role: string,
    previousAdminRole: string,
    newAdminRole: string
  ];
  export interface OutputObject {
    role: string;
    previousAdminRole: string;
    newAdminRole: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleGrantedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleRevokedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TransferEvent {
  export type InputTuple = [
    from: AddressLike,
    to: AddressLike,
    value: BigNumberish
  ];
  export type OutputTuple = [from: string, to: string, value: bigint];
  export interface OutputObject {
    from: string;
    to: string;
    value: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface CarbonCreditToken extends BaseContract {
  connect(runner?: ContractRunner | null): CarbonCreditToken;
  waitForDeployment(): Promise<this>;

  interface: CarbonCreditTokenInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  DEFAULT_ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  GOVERNMENT_ROLE: TypedContractMethod<[], [string], "view">;

  MINTER_ROLE: TypedContractMethod<[], [string], "view">;

  PROJECT_ROLE: TypedContractMethod<[], [string], "view">;

  allowance: TypedContractMethod<
    [owner: AddressLike, spender: AddressLike],
    [bigint],
    "view"
  >;

  approve: TypedContractMethod<
    [spender: AddressLike, amount: BigNumberish],
    [boolean],
    "nonpayable"
  >;

  authorizeProject: TypedContractMethod<
    [_projectContract: AddressLike],
    [void],
    "nonpayable"
  >;

  balanceOf: TypedContractMethod<[account: AddressLike], [bigint], "view">;

  burn: TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;

  burnFrom: TypedContractMethod<
    [account: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  creditBatches: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, bigint, bigint, string, string, bigint, boolean] & {
        batchId: bigint;
        projectContract: string;
        amount: bigint;
        mintTimestamp: bigint;
        projectName: string;
        landCoordinates: string;
        ndviReadingId: bigint;
        retired: boolean;
      }
    ],
    "view"
  >;

  deauthorizeProject: TypedContractMethod<
    [_projectContract: AddressLike],
    [void],
    "nonpayable"
  >;

  decimals: TypedContractMethod<[], [bigint], "view">;

  decreaseAllowance: TypedContractMethod<
    [spender: AddressLike, subtractedValue: BigNumberish],
    [boolean],
    "nonpayable"
  >;

  emergencyMint: TypedContractMethod<
    [_recipient: AddressLike, _amount: BigNumberish, _reason: string],
    [void],
    "nonpayable"
  >;

  getCreditBatch: TypedContractMethod<
    [_batchId: BigNumberish],
    [CarbonCreditToken.CreditBatchStructOutput],
    "view"
  >;

  getGlobalStats: TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint] & {
        totalMinted: bigint;
        totalRetired: bigint;
        currentSupply: bigint;
      }
    ],
    "view"
  >;

  getProjectStats: TypedContractMethod<
    [_projectContract: AddressLike],
    [bigint],
    "view"
  >;

  getRetirementRecord: TypedContractMethod<
    [_retirementId: BigNumberish],
    [CarbonCreditToken.RetirementRecordStructOutput],
    "view"
  >;

  getRoleAdmin: TypedContractMethod<[role: BytesLike], [string], "view">;

  getTotalBatches: TypedContractMethod<[], [bigint], "view">;

  getTotalRetirements: TypedContractMethod<[], [bigint], "view">;

  getUserBatches: TypedContractMethod<[_user: AddressLike], [bigint[]], "view">;

  getUserStats: TypedContractMethod<
    [_user: AddressLike],
    [[bigint, bigint] & { totalRetired: bigint; currentBalance: bigint }],
    "view"
  >;

  grantMinterRole: TypedContractMethod<
    [_account: AddressLike],
    [void],
    "nonpayable"
  >;

  grantRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  hasRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;

  increaseAllowance: TypedContractMethod<
    [spender: AddressLike, addedValue: BigNumberish],
    [boolean],
    "nonpayable"
  >;

  isAuthorizedProject: TypedContractMethod<
    [_projectContract: AddressLike],
    [boolean],
    "view"
  >;

  mintCredits: TypedContractMethod<
    [
      _projectContract: AddressLike,
      _recipient: AddressLike,
      _amount: BigNumberish,
      _projectName: string,
      _landCoordinates: string,
      _ndviReadingId: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  name: TypedContractMethod<[], [string], "view">;

  renounceRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  retireCredits: TypedContractMethod<
    [_batchId: BigNumberish, _amount: BigNumberish, _reason: string],
    [void],
    "nonpayable"
  >;

  retirements: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, bigint, bigint, string] & {
        batchId: bigint;
        retiredBy: string;
        amount: bigint;
        retirementTimestamp: bigint;
        retirementReason: string;
      }
    ],
    "view"
  >;

  revokeRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  symbol: TypedContractMethod<[], [string], "view">;

  totalMintedByProject: TypedContractMethod<
    [arg0: AddressLike],
    [bigint],
    "view"
  >;

  totalRetiredByUser: TypedContractMethod<
    [arg0: AddressLike],
    [bigint],
    "view"
  >;

  totalSupply: TypedContractMethod<[], [bigint], "view">;

  totalSupplyMinted: TypedContractMethod<[], [bigint], "view">;

  totalSupplyRetired: TypedContractMethod<[], [bigint], "view">;

  transfer: TypedContractMethod<
    [to: AddressLike, amount: BigNumberish],
    [boolean],
    "nonpayable"
  >;

  transferFrom: TypedContractMethod<
    [from: AddressLike, to: AddressLike, amount: BigNumberish],
    [boolean],
    "nonpayable"
  >;

  userBatches: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "DEFAULT_ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "GOVERNMENT_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "MINTER_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "PROJECT_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "allowance"
  ): TypedContractMethod<
    [owner: AddressLike, spender: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "approve"
  ): TypedContractMethod<
    [spender: AddressLike, amount: BigNumberish],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "authorizeProject"
  ): TypedContractMethod<[_projectContract: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "balanceOf"
  ): TypedContractMethod<[account: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "burn"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "burnFrom"
  ): TypedContractMethod<
    [account: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "creditBatches"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, bigint, bigint, string, string, bigint, boolean] & {
        batchId: bigint;
        projectContract: string;
        amount: bigint;
        mintTimestamp: bigint;
        projectName: string;
        landCoordinates: string;
        ndviReadingId: bigint;
        retired: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "deauthorizeProject"
  ): TypedContractMethod<[_projectContract: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "decimals"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "decreaseAllowance"
  ): TypedContractMethod<
    [spender: AddressLike, subtractedValue: BigNumberish],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "emergencyMint"
  ): TypedContractMethod<
    [_recipient: AddressLike, _amount: BigNumberish, _reason: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getCreditBatch"
  ): TypedContractMethod<
    [_batchId: BigNumberish],
    [CarbonCreditToken.CreditBatchStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getGlobalStats"
  ): TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint] & {
        totalMinted: bigint;
        totalRetired: bigint;
        currentSupply: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getProjectStats"
  ): TypedContractMethod<[_projectContract: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getRetirementRecord"
  ): TypedContractMethod<
    [_retirementId: BigNumberish],
    [CarbonCreditToken.RetirementRecordStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRoleAdmin"
  ): TypedContractMethod<[role: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "getTotalBatches"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getTotalRetirements"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getUserBatches"
  ): TypedContractMethod<[_user: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getUserStats"
  ): TypedContractMethod<
    [_user: AddressLike],
    [[bigint, bigint] & { totalRetired: bigint; currentBalance: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "grantMinterRole"
  ): TypedContractMethod<[_account: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "grantRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "hasRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "increaseAllowance"
  ): TypedContractMethod<
    [spender: AddressLike, addedValue: BigNumberish],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "isAuthorizedProject"
  ): TypedContractMethod<[_projectContract: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "mintCredits"
  ): TypedContractMethod<
    [
      _projectContract: AddressLike,
      _recipient: AddressLike,
      _amount: BigNumberish,
      _projectName: string,
      _landCoordinates: string,
      _ndviReadingId: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "name"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "retireCredits"
  ): TypedContractMethod<
    [_batchId: BigNumberish, _amount: BigNumberish, _reason: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "retirements"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, bigint, bigint, string] & {
        batchId: bigint;
        retiredBy: string;
        amount: bigint;
        retirementTimestamp: bigint;
        retirementReason: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "revokeRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "symbol"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "totalMintedByProject"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalRetiredByUser"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalSupply"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalSupplyMinted"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalSupplyRetired"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transfer"
  ): TypedContractMethod<
    [to: AddressLike, amount: BigNumberish],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferFrom"
  ): TypedContractMethod<
    [from: AddressLike, to: AddressLike, amount: BigNumberish],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "userBatches"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  getEvent(
    key: "Approval"
  ): TypedContractEvent<
    ApprovalEvent.InputTuple,
    ApprovalEvent.OutputTuple,
    ApprovalEvent.OutputObject
  >;
  getEvent(
    key: "CreditsMinted"
  ): TypedContractEvent<
    CreditsMintedEvent.InputTuple,
    CreditsMintedEvent.OutputTuple,
    CreditsMintedEvent.OutputObject
  >;
  getEvent(
    key: "CreditsRetired"
  ): TypedContractEvent<
    CreditsRetiredEvent.InputTuple,
    CreditsRetiredEvent.OutputTuple,
    CreditsRetiredEvent.OutputObject
  >;
  getEvent(
    key: "ProjectAuthorized"
  ): TypedContractEvent<
    ProjectAuthorizedEvent.InputTuple,
    ProjectAuthorizedEvent.OutputTuple,
    ProjectAuthorizedEvent.OutputObject
  >;
  getEvent(
    key: "ProjectDeauthorized"
  ): TypedContractEvent<
    ProjectDeauthorizedEvent.InputTuple,
    ProjectDeauthorizedEvent.OutputTuple,
    ProjectDeauthorizedEvent.OutputObject
  >;
  getEvent(
    key: "RoleAdminChanged"
  ): TypedContractEvent<
    RoleAdminChangedEvent.InputTuple,
    RoleAdminChangedEvent.OutputTuple,
    RoleAdminChangedEvent.OutputObject
  >;
  getEvent(
    key: "RoleGranted"
  ): TypedContractEvent<
    RoleGrantedEvent.InputTuple,
    RoleGrantedEvent.OutputTuple,
    RoleGrantedEvent.OutputObject
  >;
  getEvent(
    key: "RoleRevoked"
  ): TypedContractEvent<
    RoleRevokedEvent.InputTuple,
    RoleRevokedEvent.OutputTuple,
    RoleRevokedEvent.OutputObject
  >;
  getEvent(
    key: "Transfer"
  ): TypedContractEvent<
    TransferEvent.InputTuple,
    TransferEvent.OutputTuple,
    TransferEvent.OutputObject
  >;

  filters: {
    "Approval(address,address,uint256)": TypedContractEvent<
      ApprovalEvent.InputTuple,
      ApprovalEvent.OutputTuple,
      ApprovalEvent.OutputObject
    >;
    Approval: TypedContractEvent<
      ApprovalEvent.InputTuple,
      ApprovalEvent.OutputTuple,
      ApprovalEvent.OutputObject
    >;

    "CreditsMinted(uint256,address,address,uint256,string)": TypedContractEvent<
      CreditsMintedEvent.InputTuple,
      CreditsMintedEvent.OutputTuple,
      CreditsMintedEvent.OutputObject
    >;
    CreditsMinted: TypedContractEvent<
      CreditsMintedEvent.InputTuple,
      CreditsMintedEvent.OutputTuple,
      CreditsMintedEvent.OutputObject
    >;

    "CreditsRetired(uint256,uint256,address,uint256,string)": TypedContractEvent<
      CreditsRetiredEvent.InputTuple,
      CreditsRetiredEvent.OutputTuple,
      CreditsRetiredEvent.OutputObject
    >;
    CreditsRetired: TypedContractEvent<
      CreditsRetiredEvent.InputTuple,
      CreditsRetiredEvent.OutputTuple,
      CreditsRetiredEvent.OutputObject
    >;

    "ProjectAuthorized(address,address)": TypedContractEvent<
      ProjectAuthorizedEvent.InputTuple,
      ProjectAuthorizedEvent.OutputTuple,
      ProjectAuthorizedEvent.OutputObject
    >;
    ProjectAuthorized: TypedContractEvent<
      ProjectAuthorizedEvent.InputTuple,
      ProjectAuthorizedEvent.OutputTuple,
      ProjectAuthorizedEvent.OutputObject
    >;

    "ProjectDeauthorized(address,address)": TypedContractEvent<
      ProjectDeauthorizedEvent.InputTuple,
      ProjectDeauthorizedEvent.OutputTuple,
      ProjectDeauthorizedEvent.OutputObject
    >;
    ProjectDeauthorized: TypedContractEvent<
      ProjectDeauthorizedEvent.InputTuple,
      ProjectDeauthorizedEvent.OutputTuple,
      ProjectDeauthorizedEvent.OutputObject
    >;

    "RoleAdminChanged(bytes32,bytes32,bytes32)": TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;
    RoleAdminChanged: TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;

    "RoleGranted(bytes32,address,address)": TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;
    RoleGranted: TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;

    "RoleRevoked(bytes32,address,address)": TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
    RoleRevoked: TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;

    "Transfer(address,address,uint256)": TypedContractEvent<
      TransferEvent.InputTuple,
      TransferEvent.OutputTuple,
      TransferEvent.OutputObject
    >;
    Transfer: TypedContractEvent<
      TransferEvent.InputTuple,
      TransferEvent.OutputTuple,
      TransferEvent.OutputObject
    >;
  };
}
