package com.example.jaldrishti.ai

import android.util.Log
import com.example.jaldrishti.BuildConfig
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import okhttp3.MediaType.Companion.toMediaType
import okhttp3.OkHttpClient
import okhttp3.Request
import okhttp3.RequestBody.Companion.toRequestBody
import org.json.JSONArray
import org.json.JSONObject
import java.util.concurrent.TimeUnit

/**
 * OpenAI Client - Handles text generation using OpenAI API
 */
class OpenAIClient(
    private val apiKey: String = BuildConfig.OPENAI_API_KEY
) {
    private val client = OkHttpClient.Builder()
        .connectTimeout(30, TimeUnit.SECONDS)
        .readTimeout(60, TimeUnit.SECONDS)
        .writeTimeout(60, TimeUnit.SECONDS)
        .build()
    
    private val systemPrompt = """
        You are an AI assistant for a Carbon Credit ecosystem app in India.
        
        Key Information:
        - Farmers register land by walking GPS boundaries using their phone
        - They earn money from carbon credits generated by their sustainable farming
        - Payment happens the following year after credit generation
        - Emergency fund available from interest on locked credits
        - Government approves all land registrations through blockchain
        - Companies can buy carbon credits to offset their emissions
        
        Instructions:
        - Speak in simple, farmer-friendly language
        - Explain technical terms in easy to understand ways
        - Be helpful and encouraging
        - Keep responses concise (2-3 sentences max)
        - If user asks in a regional Indian language, try to respond in that language
        - Be culturally sensitive and respectful
    """.trimIndent()
    
    suspend fun chat(message: String, language: String = "English"): String = withContext(Dispatchers.IO) {
        if (apiKey.isEmpty()) {
            Log.e("OpenAIClient", "API key is empty")
            return@withContext "Please add your OpenAI API key to gradle.properties"
        }
        
        val prompt = if (language != "English") {
            "Please respond in $language language: $message"
        } else {
            message
        }
        
        try {
            val messages = JSONArray().apply {
                put(JSONObject().apply {
                    put("role", "system")
                    put("content", systemPrompt)
                })
                put(JSONObject().apply {
                    put("role", "user")
                    put("content", prompt)
                })
            }
            
            val json = JSONObject().apply {
                put("model", "openai/gpt-3.5-turbo")
                put("messages", messages)
                put("max_tokens", 256)
                put("temperature", 0.7)
            }
            
            val requestBody = json.toString().toRequestBody("application/json".toMediaType())
            
            val request = Request.Builder()
                .url("https://openrouter.ai/api/v1/chat/completions")
                .addHeader("Authorization", "Bearer $apiKey")
                .addHeader("Content-Type", "application/json")
                .addHeader("HTTP-Referer", "https://github.com/your-repo") // Optional
                .addHeader("X-Title", "Carbon Credit Assistant") // Optional
                .post(requestBody)
                .build()
            
            Log.d("OpenAIClient", "Sending request to OpenAI API")
            
            val response = client.newCall(request).execute()
            
            if (response.isSuccessful) {
                val responseBody = response.body?.string() ?: return@withContext "No response from AI"
                val jsonResponse = JSONObject(responseBody)
                
                val choices = jsonResponse.optJSONArray("choices")
                if (choices != null && choices.length() > 0) {
                    val firstChoice = choices.getJSONObject(0)
                    val message = firstChoice.optJSONObject("message")
                    val aiResponse = message?.optString("content", "") ?: ""
                    
                    Log.d("OpenAIClient", "Response received: ${aiResponse.take(100)}...")
                    aiResponse.ifEmpty { "Sorry, I couldn't generate a response." }
                } else {
                    "Sorry, I couldn't generate a response."
                }
            } else {
                val error = "Error ${response.code}: ${response.message}"
                Log.e("OpenAIClient", error)
                "Sorry, I couldn't connect to the AI service. Please check your internet connection."
            }
        } catch (e: Exception) {
            Log.e("OpenAIClient", "Connection error", e)
            "Connection error: ${e.message}. Please check your internet connection."
        }
    }
    
    suspend fun testConnection(): Boolean = withContext(Dispatchers.IO) {
        try {
            val request = Request.Builder()
                .url("https://openrouter.ai/api/v1/models")
                .addHeader("Authorization", "Bearer $apiKey")
                .get()
                .build()
            
            val response = client.newCall(request).execute()
            response.isSuccessful
        } catch (e: Exception) {
            Log.e("OpenAIClient", "Connection test failed", e)
            false
        }
    }
}