/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace ProjectContract {
  export type NDVIReadingStruct = {
    timestamp: BigNumberish;
    ndviValue: BigNumberish;
    vegetationCoverage: BigNumberish;
    carbonCreditsEarned: BigNumberish;
    satelliteImageHash: string;
    recorder: AddressLike;
    verified: boolean;
  };

  export type NDVIReadingStructOutput = [
    timestamp: bigint,
    ndviValue: bigint,
    vegetationCoverage: bigint,
    carbonCreditsEarned: bigint,
    satelliteImageHash: string,
    recorder: string,
    verified: boolean
  ] & {
    timestamp: bigint;
    ndviValue: bigint;
    vegetationCoverage: bigint;
    carbonCreditsEarned: bigint;
    satelliteImageHash: string;
    recorder: string;
    verified: boolean;
  };
}

export interface ProjectContractInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "BASE_CREDIT_RATE"
      | "DEFAULT_ADMIN_ROLE"
      | "GOVERNMENT_ROLE"
      | "MAX_CREDITS_PER_READING"
      | "MONITOR_ROLE"
      | "NDVI_THRESHOLD"
      | "NGO_ROLE"
      | "addNDVIReading"
      | "calculateCarbonCredits"
      | "getNDVIReading"
      | "getProjectProgress"
      | "getRoleAdmin"
      | "getTotalNDVIReadings"
      | "grantRole"
      | "hasRole"
      | "ndviReadings"
      | "projectData"
      | "renounceRole"
      | "revokeRole"
      | "supportsInterface"
      | "verifiedReadings"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "CarbonCreditsCalculated"
      | "NDVIReadingAdded"
      | "NDVIReadingVerified"
      | "ProjectInitialized"
      | "ProjectStatusUpdated"
      | "RoleAdminChanged"
      | "RoleGranted"
      | "RoleRevoked"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "BASE_CREDIT_RATE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "GOVERNMENT_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_CREDITS_PER_READING",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MONITOR_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "NDVI_THRESHOLD",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "NGO_ROLE", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "addNDVIReading",
    values: [BigNumberish, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "calculateCarbonCredits",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getNDVIReading",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getProjectProgress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleAdmin",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalNDVIReadings",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "grantRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "ndviReadings",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "projectData",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "renounceRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "verifiedReadings",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "BASE_CREDIT_RATE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "GOVERNMENT_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_CREDITS_PER_READING",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MONITOR_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "NDVI_THRESHOLD",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "NGO_ROLE", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "addNDVIReading",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "calculateCarbonCredits",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getNDVIReading",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getProjectProgress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRoleAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTotalNDVIReadings",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "ndviReadings",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "projectData",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifiedReadings",
    data: BytesLike
  ): Result;
}

export namespace CarbonCreditsCalculatedEvent {
  export type InputTuple = [
    readingId: BigNumberish,
    creditsEarned: BigNumberish,
    totalCredits: BigNumberish
  ];
  export type OutputTuple = [
    readingId: bigint,
    creditsEarned: bigint,
    totalCredits: bigint
  ];
  export interface OutputObject {
    readingId: bigint;
    creditsEarned: bigint;
    totalCredits: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace NDVIReadingAddedEvent {
  export type InputTuple = [
    readingId: BigNumberish,
    ndviValue: BigNumberish,
    carbonCreditsEarned: BigNumberish,
    recorder: AddressLike
  ];
  export type OutputTuple = [
    readingId: bigint,
    ndviValue: bigint,
    carbonCreditsEarned: bigint,
    recorder: string
  ];
  export interface OutputObject {
    readingId: bigint;
    ndviValue: bigint;
    carbonCreditsEarned: bigint;
    recorder: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace NDVIReadingVerifiedEvent {
  export type InputTuple = [readingId: BigNumberish, verifier: AddressLike];
  export type OutputTuple = [readingId: bigint, verifier: string];
  export interface OutputObject {
    readingId: bigint;
    verifier: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProjectInitializedEvent {
  export type InputTuple = [
    applicationId: BigNumberish,
    ngoAddress: AddressLike,
    projectName: string
  ];
  export type OutputTuple = [
    applicationId: bigint,
    ngoAddress: string,
    projectName: string
  ];
  export interface OutputObject {
    applicationId: bigint;
    ngoAddress: string;
    projectName: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProjectStatusUpdatedEvent {
  export type InputTuple = [
    oldStatus: BigNumberish,
    newStatus: BigNumberish,
    updater: AddressLike
  ];
  export type OutputTuple = [
    oldStatus: bigint,
    newStatus: bigint,
    updater: string
  ];
  export interface OutputObject {
    oldStatus: bigint;
    newStatus: bigint;
    updater: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleAdminChangedEvent {
  export type InputTuple = [
    role: BytesLike,
    previousAdminRole: BytesLike,
    newAdminRole: BytesLike
  ];
  export type OutputTuple = [
    role: string,
    previousAdminRole: string,
    newAdminRole: string
  ];
  export interface OutputObject {
    role: string;
    previousAdminRole: string;
    newAdminRole: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleGrantedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleRevokedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ProjectContract extends BaseContract {
  connect(runner?: ContractRunner | null): ProjectContract;
  waitForDeployment(): Promise<this>;

  interface: ProjectContractInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  BASE_CREDIT_RATE: TypedContractMethod<[], [bigint], "view">;

  DEFAULT_ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  GOVERNMENT_ROLE: TypedContractMethod<[], [string], "view">;

  MAX_CREDITS_PER_READING: TypedContractMethod<[], [bigint], "view">;

  MONITOR_ROLE: TypedContractMethod<[], [string], "view">;

  NDVI_THRESHOLD: TypedContractMethod<[], [bigint], "view">;

  NGO_ROLE: TypedContractMethod<[], [string], "view">;

  addNDVIReading: TypedContractMethod<
    [
      _ndviValue: BigNumberish,
      _vegetationCoverage: BigNumberish,
      _satelliteImageHash: string
    ],
    [void],
    "nonpayable"
  >;

  calculateCarbonCredits: TypedContractMethod<
    [_ndviValue: BigNumberish],
    [bigint],
    "view"
  >;

  getNDVIReading: TypedContractMethod<
    [_readingId: BigNumberish],
    [ProjectContract.NDVIReadingStructOutput],
    "view"
  >;

  getProjectProgress: TypedContractMethod<[], [bigint], "view">;

  getRoleAdmin: TypedContractMethod<[role: BytesLike], [string], "view">;

  getTotalNDVIReadings: TypedContractMethod<[], [bigint], "view">;

  grantRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  hasRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;

  ndviReadings: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, bigint, bigint, string, string, boolean] & {
        timestamp: bigint;
        ndviValue: bigint;
        vegetationCoverage: bigint;
        carbonCreditsEarned: bigint;
        satelliteImageHash: string;
        recorder: string;
        verified: boolean;
      }
    ],
    "view"
  >;

  projectData: TypedContractMethod<
    [],
    [
      [
        bigint,
        string,
        string,
        bigint,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        applicationId: bigint;
        projectName: string;
        landCoordinates: string;
        areaHectares: bigint;
        plantSpecies: string;
        ngoAddress: string;
        governmentApprover: string;
        createdAt: bigint;
        startDate: bigint;
        expectedCompletionDate: bigint;
        status: bigint;
        targetCarbonCredits: bigint;
        totalCarbonCreditsEarned: bigint;
      }
    ],
    "view"
  >;

  renounceRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  revokeRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  verifiedReadings: TypedContractMethod<
    [arg0: BigNumberish],
    [boolean],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "BASE_CREDIT_RATE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "DEFAULT_ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "GOVERNMENT_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "MAX_CREDITS_PER_READING"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MONITOR_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "NDVI_THRESHOLD"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "NGO_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "addNDVIReading"
  ): TypedContractMethod<
    [
      _ndviValue: BigNumberish,
      _vegetationCoverage: BigNumberish,
      _satelliteImageHash: string
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "calculateCarbonCredits"
  ): TypedContractMethod<[_ndviValue: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getNDVIReading"
  ): TypedContractMethod<
    [_readingId: BigNumberish],
    [ProjectContract.NDVIReadingStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getProjectProgress"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getRoleAdmin"
  ): TypedContractMethod<[role: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "getTotalNDVIReadings"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "grantRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "hasRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "ndviReadings"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, bigint, bigint, string, string, boolean] & {
        timestamp: bigint;
        ndviValue: bigint;
        vegetationCoverage: bigint;
        carbonCreditsEarned: bigint;
        satelliteImageHash: string;
        recorder: string;
        verified: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "projectData"
  ): TypedContractMethod<
    [],
    [
      [
        bigint,
        string,
        string,
        bigint,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        applicationId: bigint;
        projectName: string;
        landCoordinates: string;
        areaHectares: bigint;
        plantSpecies: string;
        ngoAddress: string;
        governmentApprover: string;
        createdAt: bigint;
        startDate: bigint;
        expectedCompletionDate: bigint;
        status: bigint;
        targetCarbonCredits: bigint;
        totalCarbonCreditsEarned: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "renounceRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "verifiedReadings"
  ): TypedContractMethod<[arg0: BigNumberish], [boolean], "view">;

  getEvent(
    key: "CarbonCreditsCalculated"
  ): TypedContractEvent<
    CarbonCreditsCalculatedEvent.InputTuple,
    CarbonCreditsCalculatedEvent.OutputTuple,
    CarbonCreditsCalculatedEvent.OutputObject
  >;
  getEvent(
    key: "NDVIReadingAdded"
  ): TypedContractEvent<
    NDVIReadingAddedEvent.InputTuple,
    NDVIReadingAddedEvent.OutputTuple,
    NDVIReadingAddedEvent.OutputObject
  >;
  getEvent(
    key: "NDVIReadingVerified"
  ): TypedContractEvent<
    NDVIReadingVerifiedEvent.InputTuple,
    NDVIReadingVerifiedEvent.OutputTuple,
    NDVIReadingVerifiedEvent.OutputObject
  >;
  getEvent(
    key: "ProjectInitialized"
  ): TypedContractEvent<
    ProjectInitializedEvent.InputTuple,
    ProjectInitializedEvent.OutputTuple,
    ProjectInitializedEvent.OutputObject
  >;
  getEvent(
    key: "ProjectStatusUpdated"
  ): TypedContractEvent<
    ProjectStatusUpdatedEvent.InputTuple,
    ProjectStatusUpdatedEvent.OutputTuple,
    ProjectStatusUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "RoleAdminChanged"
  ): TypedContractEvent<
    RoleAdminChangedEvent.InputTuple,
    RoleAdminChangedEvent.OutputTuple,
    RoleAdminChangedEvent.OutputObject
  >;
  getEvent(
    key: "RoleGranted"
  ): TypedContractEvent<
    RoleGrantedEvent.InputTuple,
    RoleGrantedEvent.OutputTuple,
    RoleGrantedEvent.OutputObject
  >;
  getEvent(
    key: "RoleRevoked"
  ): TypedContractEvent<
    RoleRevokedEvent.InputTuple,
    RoleRevokedEvent.OutputTuple,
    RoleRevokedEvent.OutputObject
  >;

  filters: {
    "CarbonCreditsCalculated(uint256,uint256,uint256)": TypedContractEvent<
      CarbonCreditsCalculatedEvent.InputTuple,
      CarbonCreditsCalculatedEvent.OutputTuple,
      CarbonCreditsCalculatedEvent.OutputObject
    >;
    CarbonCreditsCalculated: TypedContractEvent<
      CarbonCreditsCalculatedEvent.InputTuple,
      CarbonCreditsCalculatedEvent.OutputTuple,
      CarbonCreditsCalculatedEvent.OutputObject
    >;

    "NDVIReadingAdded(uint256,uint256,uint256,address)": TypedContractEvent<
      NDVIReadingAddedEvent.InputTuple,
      NDVIReadingAddedEvent.OutputTuple,
      NDVIReadingAddedEvent.OutputObject
    >;
    NDVIReadingAdded: TypedContractEvent<
      NDVIReadingAddedEvent.InputTuple,
      NDVIReadingAddedEvent.OutputTuple,
      NDVIReadingAddedEvent.OutputObject
    >;

    "NDVIReadingVerified(uint256,address)": TypedContractEvent<
      NDVIReadingVerifiedEvent.InputTuple,
      NDVIReadingVerifiedEvent.OutputTuple,
      NDVIReadingVerifiedEvent.OutputObject
    >;
    NDVIReadingVerified: TypedContractEvent<
      NDVIReadingVerifiedEvent.InputTuple,
      NDVIReadingVerifiedEvent.OutputTuple,
      NDVIReadingVerifiedEvent.OutputObject
    >;

    "ProjectInitialized(uint256,address,string)": TypedContractEvent<
      ProjectInitializedEvent.InputTuple,
      ProjectInitializedEvent.OutputTuple,
      ProjectInitializedEvent.OutputObject
    >;
    ProjectInitialized: TypedContractEvent<
      ProjectInitializedEvent.InputTuple,
      ProjectInitializedEvent.OutputTuple,
      ProjectInitializedEvent.OutputObject
    >;

    "ProjectStatusUpdated(uint8,uint8,address)": TypedContractEvent<
      ProjectStatusUpdatedEvent.InputTuple,
      ProjectStatusUpdatedEvent.OutputTuple,
      ProjectStatusUpdatedEvent.OutputObject
    >;
    ProjectStatusUpdated: TypedContractEvent<
      ProjectStatusUpdatedEvent.InputTuple,
      ProjectStatusUpdatedEvent.OutputTuple,
      ProjectStatusUpdatedEvent.OutputObject
    >;

    "RoleAdminChanged(bytes32,bytes32,bytes32)": TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;
    RoleAdminChanged: TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;

    "RoleGranted(bytes32,address,address)": TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;
    RoleGranted: TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;

    "RoleRevoked(bytes32,address,address)": TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
    RoleRevoked: TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
  };
}
